---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/8/7 19:11
---

local key = KEYS[1]
local newUnlockTime = ARGV[1]
local owner = ARGV[2]
local currentTime = tonumber(ARGV[3])
local value = redis.call('HGET', key, 'value')
local unlockTime = redis.call('HGET', key, 'unlockTime')
local lockOwner = redis.call('HGET', key, 'owner')
local lockInfo = redis.call('HGET', key, 'lockInfo')

-- 锁已过期，直接上锁进行加载数据
if unlockTime and currentTime > tonumber(unlockTime) then
    redis.call('HMSET', key, 'lockInfo', 'locked', 'unlockTime', newUnlockTime, 'owner', owner)
    return { value, 'NEED_QUERY' }
end


-- 缓存中没有值的情况下
-- 1.如果已经上锁 则进行等待
-- 2.如果没有上锁 则上锁进行加载数据
if not value or value == '' then
    if lockOwner and lockOwner ~= owner then
        return { value, 'NEED_WAIT' }
    end
    redis.call('HMSET', key, 'lockInfo', 'locked', 'unlockTime', newUnlockTime, 'owner', owner)
    return { value, 'NEED_QUERY' }
end

-- 缓存中有值的情况下，直接返回。这里的缓存可能是旧值，需要异步进行获取数据
if lockInfo and lockInfo == 'locked' then
    return { value, 'SUCCESS_NEED_QUERY' }
end

return { value, 'SUCCESS' }
