---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/8/7 19:11
---

local key = KEYS[1]
local newUnlockTime = tonumber(ARGV[1])
-- 阻止读请求 设置缓存SetCache
redis.call('HDEL', key, 'owner')
local value = redis.call('HGET', key, 'value')
redis.call('HSET', key, 'lockInfo', 'locked')

if not value or value == '' then
    return { true, 'EMPTY_VALUE_SUCCESS' }
end

if newUnlockTime > 0 then
    redis.call('HSET', key, 'unlockTime', newUnlockTime)
end

return { '', 'SUCCESS' }
