---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/8/7 19:48
---

local key = KEYS[1]
local value = ARGV[1]
local currentOwner = ARGV[2]
local expire = ARGV[3]

local owner = redis.call('HGET', key, 'owner')
if owner ~= currentOwner then
    return
end
redis.call('HSET', key, 'value', value)
redis.call('EXPIRE', key, expire)
-- 解锁
redis.call('HDEL', key, 'unlockTime')
redis.call('HDEL', key, 'owner')
redis.call('HDEL', key, 'lockInfo')